### ISSUE TITLE
Object::download does not return error if object does not exist

### ISSUE THREAD

**Issue by milenkovicm** [ThouCheese/cloud-storage-rs#56]
Based on my understanding

```rust
val object = Object::download(&self.bucket.name, path.as_ref()).await?;
```

should return object if available or error (Error::Google) in case it does not. 

When tested with file which does not exist:

```
debug!("{:?}", String::from_utf8(object.clone()).unwrap());
```

prints:

```
No such object: whatever_object_name
```

log clearly says that file is `404`

```
DEBUG reqwest::async_impl::client  > response '404 Not Found' for https://www.googleapis.com/storage/...
```

Am I missing something or there is problem with `download` method ?

Using latest `0.7` version

Thanks

**Comment by milenkovicm** [comment]
this issue is probably covered with #47

**Comment by ThouCheese** [comment]
Hi @milenkovicm, Yes, #47 would solve the issue. The PR is currently stalled because I requested some changes from @nhynes. We can see if he wakes up from this ping and resolves the issues, and if not I will merge the PR next week (because it is good work) and resolve the issues myself.

**Comment by nhynes** [comment]
Hello, I am awake! I must have missed the notification on that last PR. I'll attend to it promptly. Thanks for your patience.

**Comment by ThouCheese** [comment]
No worries!

**Comment by ThouCheese** [comment]
`cloud-storage 0.7.1` is now released and it should fix this, can you confirm that the issue is solved?

**Comment by milenkovicm** [comment]
It looks like partially fixed.

The response it returns when object is not available is  `Reqwest(reqwest::Error { kind: Status(404) ...)}`, but based on error documentation `Google(GoogleErrorResponse)` should be returned in this case, which make more sense IMHO

**Comment by ThouCheese** [comment]
The response body returned by Google in this case is `No such object: <bucket>/<file>`.  There is no GoogleErrorResponse to parse in this case. I think the rationale (used by google) is that this is not an endpoint of their JSON API, so they don't return a JSON error either.

**Comment by ThouCheese** [comment]
I suppose that the most meaningful thing to do here is to wrap the response message in `Error::Other`

**Comment by ThouCheese** [comment]
This is now released as of `0.8.2`
