### ISSUE TITLE
The library cannot deserialize Bucket::list()

### ISSUE THREAD

**Issue by doivosevic** [ThouCheese/cloud-storage-rs#66]
I'm getting a response 
```

&buckets = Err(
    Reqwest(
        reqwest::Error {
            kind: Decode,
            source: Error("data did not match any variant of untagged enum GoogleResponse", line: 0, column: 0),
        },
    ),
)

```

I'm pretty sure I have the correct rights as when I didn't have them I was receiving an empty list. I am yet to manage to find out what is actually then returned as a response for this request

**Comment by ThouCheese** [comment]
You are right, this is a bug. The issue is that google is returning a number delimited by quotes, whereas the library was expecting a number. Fixed in release `0.8.2`!

**Comment by doivosevic** [comment]
Hey! I really appreciate the quick response and update. Unfortunately this issue wasn't fixed for me in 0.8.2

**Comment by doivosevic** [comment]
@ThouCheese I'm getting this as a response from the GCloud API 
```

{
  \"kind\": \"storage#buckets\",
  \"items\": [
    {
      \"kind\": \"storage#bucket\",
      \"selfLink\": \"https://www.googleapis.com/storage/v1/b/qwe\",
      \"id\": \"qwe\",
      \"name\": \"qwe\",
      \"projectNumber\": \"qwe\",
      \"metageneration\": \"4\",
      \"location\": \"EUROPE-WEST2\",
      \"storageClass\": \"STANDARD\",
      \"etag\": \"CAQ=\",
      \"defaultEventBasedHold\": false,
      \"timeCreated\": \"2021-02-10T10:19:55.919Z\",
      \"updated\": \"2021-03-10T11:34:27.925Z\",
      \"iamConfiguration\": {
        \"bucketPolicyOnly\": {
          \"enabled\": false
        },
        \"uniformBucketLevelAccess\": {
          \"enabled\": false
        }
      },
      \"locationType\": \"region\",
      \"satisfiesPZS\": false
    },
    {
      \"kind\": \"storage#bucket\",
      \"selfLink\": \"https://www.googleapis.com/storage/v1/b/qwe\",
      \"id\": \"qwe\",
      \"name\": \"qwe\",
      \"projectNumber\": \"qwe\",
      \"metageneration\": \"4\",
      \"location\": \"EUROPE-WEST2\",
      \"storageClass\": \"STANDARD\",
      \"etag\": \"CAQ=\",
      \"defaultEventBasedHold\": false,
      \"timeCreated\": \"2020-12-10T11:15:29.555Z\",
      \"updated\": \"2021-03-10T11:34:27.927Z\",
      \"iamConfiguration\": {
        \"bucketPolicyOnly\": {
          \"enabled\": false
        },
        \"uniformBucketLevelAccess\": {
          \"enabled\": false
        }
      },
      \"locationType\": \"region\",
      \"satisfiesPZS\": false
    },
    {
      \"kind\": \"storage#bucket\",
      \"selfLink\": \"https://www.googleapis.com/storage/v1/b/qwe\",
      \"id\": \"qwe\",
      \"name\": \"qwe\",
      \"projectNumber\": \"qwe\",
      \"metageneration\": \"3\",
      \"location\": \"EUROPE-WEST2\",
      \"storageClass\": \"STANDARD\",
      \"etag\": \"CAM=\",
      \"defaultEventBasedHold\": false,
      \"timeCreated\": \"2020-12-10T11:16:09.838Z\",
      \"updated\": \"2021-03-10T11:34:27.925Z\",
      \"iamConfiguration\": {
        \"bucketPolicyOnly\": {
          \"enabled\": false
        },
        \"uniformBucketLevelAccess\": {
          \"enabled\": false
        }
      },
      \"locationType\": \"region\",
      \"satisfiesPZS\": false
    },
    {
      \"kind\": \"storage#bucket\",
      \"selfLink\": \"https://www.googleapis.com/storage/v1/b/qwe\",
      \"id\": \"qwe\",
      \"name\": \"qwe\",
      \"projectNumber\": \"qwe\",
      \"metageneration\": \"16\",
      \"location\": \"EU\",
      \"storageClass\": \"STANDARD\",
      \"etag\": \"CBA=\",
      \"defaultEventBasedHold\": false,
      \"timeCreated\": \"2020-03-30T07:31:24.720Z\",
      \"updated\": \"2021-03-10T11:34:28.394Z\",
      \"billing\": {
        \"requesterPays\": false
      },
      \"iamConfiguration\": {
        \"bucketPolicyOnly\": {
          \"enabled\": false
        },
        \"uniformBucketLevelAccess\": {
          \"enabled\": false
        }
      },
      \"locationType\": \"multi-region\"
    },
    {
      \"kind\": \"storage#bucket\",
      \"selfLink\": \"https://www.googleapis.com/storage/v1/b/qwe\",
      \"id\": \"qwe\",
      \"name\": \"qwe\",
      \"projectNumber\": \"qwe\",
      \"metageneration\": \"2\",
      \"location\": \"EUROPE-WEST1\",
      \"storageClass\": \"REGIONAL\",
      \"etag\": \"CAI=\",
      \"timeCreated\": \"2017-05-03T12:32:16.018Z\",
      \"updated\": \"2021-03-10T11:34:27.927Z\",
      \"locationType\": \"region\"
    },
    {
      \"kind\": \"storage#bucket\",
      \"selfLink\": \"https://www.googleapis.com/storage/v1/b/qwe-sorted\",
      \"id\": \"qwe-sorted\",
      \"name\": \"qwe-sorted\",
      \"projectNumber\": \"qwe\",
      \"metageneration\": \"2\",
      \"location\": \"EUROPE-WEST1\",
      \"storageClass\": \"REGIONAL\",
      \"etag\": \"CAI=\",
      \"timeCreated\": \"2017-07-26T03:43:33.087Z\",
      \"updated\": \"2021-03-10T11:34:27.925Z\",
      \"locationType\": \"region\"
    },
    {
      \"kind\": \"storage#bucket\",
      \"selfLink\": \"https://www.googleapis.com/storage/v1/b/qwedta\",
      \"id\": \"qwedta\",
      \"name\": \"qwedta\",
      \"projectNumber\": \"qwe\",
      \"metageneration\": \"13\",
      \"location\": \"EUROPE-WEST2\",
      \"storageClass\": \"STANDARD\",
      \"etag\": \"CA0=\",
      \"defaultEventBasedHold\": false,
      \"timeCreated\": \"2019-11-05T12:48:54.709Z\",
      \"updated\": \"2021-03-16T11:42:58.331Z\",
      \"iamConfiguration\": {
        \"bucketPolicyOnly\": {
          \"enabled\": false
        },
        \"uniformBucketLevelAccess\": {
          \"enabled\": false
        }
      },
      \"locationType\": \"region\"
    },
    {
      \"kind\": \"storage#bucket\",
      \"selfLink\": \"https://www.googleapis.com/storage/v1/b/qwe\",
      \"id\": \"qwe\",
      \"name\": \"qwe\",
      \"projectNumber\": \"qwe\",
      \"metageneration\": \"4\",
      \"location\": \"EUROPE-WEST1\",
      \"storageClass\": \"REGIONAL\",
      \"etag\": \"CAQ=\",
      \"timeCreated\": \"2018-01-23T15:06:59.617Z\",
      \"updated\": \"2021-03-10T11:34:27.928Z\",
      \"iamConfiguration\": {
        \"bucketPolicyOnly\": {
          \"enabled\": false
        },
        \"uniformBucketLevelAccess\": {
          \"enabled\": false
        }
      },
      \"locationType\": \"region\"
    },
    {
      \"kind\": \"storage#bucket\",
      \"selfLink\": \"https://www.googleapis.com/storage/v1/b/qwe\",
      \"id\": \"qwe\",
      \"name\": \"qwe\",
      \"projectNumber\": \"qwe\",
      \"metageneration\": \"11\",
      \"location\": \"EUROPE-WEST2\",
      \"storageClass\": \"REGIONAL\",
      \"etag\": \"CAs=\",
      \"timeCreated\": \"2018-04-27T11:10:37.802Z\",
      \"updated\": \"2021-03-10T11:34:27.928Z\",
      \"iamConfiguration\": {
        \"bucketPolicyOnly\": {
          \"enabled\": false
        },
        \"uniformBucketLevelAccess\": {
          \"enabled\": false
        }
      },
      \"locationType\": \"region\"
    }
  ]
}

```

**Comment by ThouCheese** [comment]
Reopening then, lets see what I can do with your data, thanks

**Comment by doivosevic** [comment]
It seems like the ListResponse is missing "kind" property and some buckets do not have specified the iamConfiguration among other things so that needs to be optional

**Comment by doivosevic** [comment]
I'm not sure what "writable" means as a note in this case but I think that this means these fields are optional on a bucket https://cloud.google.com/storage/docs/json_api/v1/buckets

**Comment by ThouCheese** [comment]
> It seems like the ListResponse is missing "kind" property
I can see the kind parameter on the top of the JSON you posted: `\"kind\": \"storage#buckets\",`. I think that the problem is the missing `iamConfiguration`. I will release a new version that is able to parse the sample response you just posted, and then I think the issue should be resolved.

**Comment by ThouCheese** [comment]
Version `0.8.3` is out, can you confirm that the issue is resolved>

**Comment by doivosevic** [comment]
Yep. It works now. Thanks
